class BangleExecutor{

    public static void main(String[] args){

        System.out.println(" Default Constructor Objects");

        Bangle ref1=new Bangle(); 
		ref1.size=1; 
		System.out.println(ref1.size);
        Bangle ref2=new Bangle(); 
		ref2.size=2; 
		System.out.println(ref2.size);
        Bangle ref3=new Bangle();
		ref3.size=3; 
		System.out.println(ref3.size);
        Bangle ref4=new Bangle();
		ref4.size=4;
		System.out.println(ref4.size);
        Bangle ref5=new Bangle(); 
		ref5.size=5;
		System.out.println(ref5.size);
        Bangle ref6=new Bangle();
		ref6.size=6;
		System.out.println(ref6.size);
        Bangle ref7=new Bangle();
		ref7.size=7; 
		System.out.println(ref7.size);
        Bangle ref8=new Bangle();
		ref8.size=8;
		System.out.println(ref8.size);
        Bangle ref9=new Bangle(); 
		ref9.size=9;
		System.out.println(ref9.size);
        Bangle ref10=new Bangle(); 
		ref10.size=10; 
		System.out.println(ref10.size);
        Bangle ref11=new Bangle();
		ref11.size=11;
		System.out.println(ref11.size);
        Bangle ref12=new Bangle();
		ref12.size=12; 
		System.out.println(ref12.size);
        Bangle ref13=new Bangle();
		ref13.size=13; 
		System.out.println(ref13.size);
        Bangle ref14=new Bangle();
		ref14.size=14;
		System.out.println(ref14.size);
        Bangle ref15=new Bangle(); 
		ref15.size=15; 
		System.out.println(ref15.size);
        Bangle ref16=new Bangle();
		ref16.size=16; 
		System.out.println(ref16.size);
        Bangle ref17=new Bangle();
		ref17.size=17; 
		System.out.println(ref17.size);
        Bangle ref18=new Bangle(); 
		ref18.size=18; 
		System.out.println(ref18.size);
        Bangle ref19=new Bangle(); 
		ref19.size=19; 
		System.out.println(ref19.size);
        Bangle ref20=new Bangle();
		ref20.size=20;
		System.out.println(ref20.size);
        Bangle ref21=new Bangle();
		ref21.size=21; 
		System.out.println(ref21.size);
        Bangle ref22=new Bangle();
		ref22.size=22;
		System.out.println(ref22.size);
        Bangle ref23=new Bangle(); 
		ref23.size=23; 
		System.out.println(ref23.size);
        Bangle ref24=new Bangle();
		ref24.size=24; 
		System.out.println(ref24.size);
        Bangle ref25=new Bangle();
		ref25.size=25; 
		System.out.println(ref25.size);


        System.out.println(" Parameterized Constructor Objects ");

        Bangle p1=new Bangle(26);
		System.out.println(p1.size);
        Bangle p2=new Bangle(27);
		System.out.println(p2.size);
        Bangle p3=new Bangle(28); 
		System.out.println(p3.size);
        Bangle p4=new Bangle(29); 
		System.out.println(p4.size);
        Bangle p5=new Bangle(30); 
		System.out.println(p5.size);
        Bangle p6=new Bangle(31);
		System.out.println(p6.size);
        Bangle p7=new Bangle(32);
		System.out.println(p7.size);
        Bangle p8=new Bangle(33); 
		System.out.println(p8.size);
        Bangle p9=new Bangle(34); 
		System.out.println(p9.size);
        Bangle p10=new Bangle(35); 
		System.out.println(p10.size);
        Bangle p11=new Bangle(36); 
		System.out.println(p11.size);
        Bangle p12=new Bangle(37); 
		System.out.println(p12.size);
        Bangle p13=new Bangle(38);
		System.out.println(p13.size);
        Bangle p14=new Bangle(39);
		System.out.println(p14.size);
        Bangle p15=new Bangle(40); 
		System.out.println(p15.size);
        Bangle p16=new Bangle(41);
		System.out.println(p16.size);
        Bangle p17=new Bangle(42);
		System.out.println(p17.size);
        Bangle p18=new Bangle(43);
		System.out.println(p18.size);
        Bangle p19=new Bangle(44);
		System.out.println(p19.size);
        Bangle p20=new Bangle(45);
		System.out.println(p20.size);
        Bangle p21=new Bangle(46);
		System.out.println(p21.size);
        Bangle p22=new Bangle(47); 
		System.out.println(p22.size);
        Bangle p23=new Bangle(48); 
		System.out.println(p23.size);
        Bangle p24=new Bangle(49);
		System.out.println(p24.size);
        Bangle p25=new Bangle(50); 
		System.out.println(p25.size);

    }
}